from pyst import *

data = [1, 3, -24, 13, .133131, .24, 4512451, .2]
print mean(data)
print stdev(data)
print mode(data)
print median(data)
print pstdev(data)
print variance(data)
print pvariance(data)
print md(data)
print mad(data)
print adev(data, data[0])
print adev(data, mode)
print adev(data, stdev(data))
print id(data)
print kurtosis(data)
print skewness(data)
print range(data)
print quartiles(data, 0)
print quartiles(data, 1)
print quartiles(data, 2)
print quartiles(data, 3)
print quartiles(data, 4)
print quantiles(data, 0)
print quantiles(data, 1)
print quantiles(data, 2)
print quantiles(data, 3)
print quantiles(data, 4)
print quantiles(data, 5)
print quantiles(data, 6)
print quantiles(data, 7)
print quantiles(data, 8)
print quantiles(data, 9)